import { expect, test } from "@playwright/test";
import { examplePipeline } from "../../packages/pipeline-model";
import { menuAction } from "./ide-helpers";

test("Navigator follows workspace node types and preserves state when docking", async ({ page }) => {
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  const document = examplePipeline();
  await page.route("**/studio-team/v1/session", route => route.fulfill({ json: { authenticated: true, mode: "local", actor: { id: "viewer", workspaceIds: ["local"], scopes: ["pipelines.read", "runs.read"] } } }));
  await page.route("**/studio-monitoring/v1/session", route => route.fulfill({ json: { token: "test" } }));
  await page.route("**/studio-monitoring/v1/commands", route => {
    const { name, input } = route.request().postDataJSON(); expect(name).toBe("monitoring.snapshot");
    return route.fulfill({ json: { result: { workspaceId: "local", observedAt: new Date().toISOString(), pipelines: input.pipelineId ? [] : [{ id: "second-pipeline", name: "Second pipeline", graphRevision: 1, nodes: [{ id: "observer", type: "test.observer", typeVersion: "1", label: "External observer", kind: "unavailable" }] }], runs: [] } } });
  });
  await page.goto("/");
  await menuAction(page, "视图", "停靠 Navigator");
  const monitor = page.getByRole("region", { name: "Navigator 运行监控" });
  await expect(monitor.getByLabel("监控范围")).toHaveValue("workspace");
  await expect(monitor.getByRole("tab", { name: /test.observer/ })).toBeVisible();
  await monitor.getByRole("tab", { name: /test.observer/ }).click();
  await expect(monitor.getByRole("button", { name: /External observer/ })).toBeVisible();
  await monitor.getByLabel("固定查看").check();
  await monitor.getByLabel("筛选监控节点").fill("External");
  await monitor.getByRole("button", { name: "在主区域打开" }).click();
  await expect(page.getByRole("tab", { name: "Navigator", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(monitor.getByLabel("筛选监控节点")).toHaveValue("External");
  await monitor.getByRole("button", { name: "停靠右侧" }).click();
  await expect(monitor.getByLabel("固定查看")).toBeChecked();
  await monitor.getByLabel("监控范围").selectOption("pipeline");
  await expect(monitor.getByRole("tab", { name: /test.observer/ })).toHaveCount(0);
  await monitor.getByLabel("筛选监控节点").fill("");
  await monitor.getByRole("tab", { name: /训练/ }).click();
  await expect(monitor.getByRole("button", { name: new RegExp(document.nodes.find(node => node.id === "training")!.label) })).toBeVisible();
  await page.screenshot({ path: "test-results/navigator-docked.png" });
  await monitor.getByRole("button", { name: "在主区域打开" }).click();
  await page.getByLabel("语言", { exact: true }).selectOption("en-US");
  await expect(page.getByLabel("Monitoring scope")).toHaveValue("pipeline");
  await page.screenshot({ path: "test-results/navigator-expanded.png" });
  expect(errors).toEqual([]);
});

test("legacy management links open in Studio and page switching retains unfinished forms", async ({ page }) => {
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  await page.route("**/api/v1/**", route => {
    const path = new URL(route.request().url()).pathname;
    if (path === "/api/v1/auth/session") return route.fulfill({ json: { authenticated: true, state: "AUTHENTICATED", sessionId: "test", expiresAt: "2099-01-01T00:00:00Z", refreshExpiresAt: "2099-01-02T00:00:00Z", refreshable: true, csrfToken: "test", refreshed: false } });
    return route.fulfill({ json: [] });
  });
  await page.goto("/datasets");
  await expect(page.getByRole("navigation", { name: "主菜单" })).toBeVisible();
  const input = page.getByPlaceholder("instruction-tuning-v1").first();
  await input.fill("keep-my-dataset-draft");
  await page.getByRole("tab", { name: "结构化准备", exact: true }).click();
  await expect(input).toBeHidden();
  await page.getByRole("tab", { name: "文档工作台", exact: true }).click();
  await expect(input).toBeHidden();
  await page.getByRole("tab", { name: "数据集与版本", exact: true }).click();
  await expect(input).toHaveValue("keep-my-dataset-draft");
  const editorArea = page.locator(".ide-editor-area");
  await page.getByRole("tab", { name: "数据集管理", exact: true }).dragTo(editorArea, { targetPosition: { x: (await editorArea.boundingBox())!.width - 12, y: 130 } });
  await expect(input).toHaveValue("keep-my-dataset-draft");
  await menuAction(page, "视图", "合并编辑区");
  await expect(input).toHaveValue("keep-my-dataset-draft");
  await menuAction(page, "工具", "模型管理");
  await expect(input).toBeHidden();
  await menuAction(page, "工具", "数据集管理");
  await expect(input).toHaveValue("keep-my-dataset-draft");
  await page.getByLabel("语言", { exact: true }).selectOption("en-US");
  await expect(input).toHaveValue("keep-my-dataset-draft");
  await page.screenshot({ path: "test-results/studio-management.png" });
  expect(errors).toEqual([]);
});


test("dragged editor tabs split either side, merge and preserve documents with single-group defaults", async ({ page }) => {
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  await page.route("**/studio-team/v1/session", route => route.fulfill({ json: { authenticated: true, mode: "local", actor: { id: "viewer", workspaceIds: ["local"], scopes: ["pipelines.read", "runs.read"] } } }));
  await page.route("**/studio-monitoring/v1/session", route => route.fulfill({ json: { token: "test" } }));
  await page.route("**/studio-monitoring/v1/commands", route => route.fulfill({ json: { result: { workspaceId: "local", observedAt: new Date().toISOString(), pipelines: [], runs: [] } } }));
  await page.goto("/");
  await page.getByLabel("训练轮数").fill("8");
  const canvas = page.locator(".canvas-container canvas");
  await canvas.evaluate(element => element.setAttribute("data-instance", "original"));
  await page.getByRole("button", { name: "Navigator 运行监控", exact: true }).click();
  const monitor = page.getByRole("region", { name: "Navigator 运行监控" });
  await monitor.getByLabel("固定查看").check();
  await monitor.getByLabel("监控范围").selectOption("pipeline");
  await monitor.getByLabel("筛选监控节点").fill("训练");
  const area = page.locator(".ide-editor-area");
  const navTab = page.getByRole("tab", { name: "Navigator", exact: true });
  await expect(page.getByRole("separator", { name: "调整编辑区分栏宽度" })).toHaveCount(0);
  const areaBox = (await area.boundingBox())!;
  const tabBox = (await navTab.boundingBox())!;
  await page.mouse.move(tabBox.x + 20, tabBox.y + 15); await page.mouse.down();
  await page.mouse.move(tabBox.x + 35, tabBox.y + 35, { steps: 3 });
  await page.mouse.move(areaBox.x + areaBox.width - 12, areaBox.y + 130, { steps: 5 });
  await expect(page.locator(".ide-editor-drop.right")).toBeVisible();
  await page.keyboard.press("Escape"); await page.mouse.up();
  await expect(page.locator(".ide-editor-drop")).toHaveCount(0);
  await expect(page.getByRole("separator", { name: "调整编辑区分栏宽度" })).toHaveCount(0);
  await navTab.dragTo(area, { targetPosition: { x: areaBox.width - 12, y: 130 } });
  const divider = page.getByRole("separator", { name: "调整编辑区分栏宽度" });
  await expect(divider).toBeVisible();
  await expect(page.locator("[data-editor-group='1']").getByRole("region")).toBeVisible();
  await expect(canvas).toHaveAttribute("data-instance", "original");
  await expect(monitor.getByLabel("筛选监控节点")).toHaveValue("训练");
  await expect(monitor.getByLabel("固定查看")).toBeChecked();
  const graphBox = (await canvas.boundingBox())!, monitorBox = (await monitor.boundingBox())!;
  expect(graphBox.x + graphBox.width).toBeLessThanOrEqual(monitorBox.x);
  expect(Math.min(graphBox.y + graphBox.height, monitorBox.y + monitorBox.height) - Math.max(graphBox.y, monitorBox.y)).toBeGreaterThan(150);
  const before = Number(await divider.getAttribute("aria-valuenow"));
  await divider.focus(); await divider.press("ArrowRight");
  await expect.poll(async () => Number(await divider.getAttribute("aria-valuenow"))).toBe(before + 16);
  const handle = (await divider.boundingBox())!;
  await page.mouse.move(handle.x + 2, handle.y + 80); await page.mouse.down();
  await page.mouse.move(handle.x - 48, handle.y + 80, { steps: 5 }); await page.mouse.up();
  await expect.poll(async () => Number(await divider.getAttribute("aria-valuenow"))).toBe(before - 34);
  const ratio = await page.evaluate(() => JSON.parse(localStorage.getItem("cyrene.studio.layout.v1")!).editorRatio);
  await page.getByRole("tab", { name: "JSON", exact: true }).click();
  const draft = await page.getByLabel("文件内容预览").innerText();
  expect(JSON.parse(draft).nodes.find((node: { id: string }) => node.id === "training").config.epochs).toBe(8);
  await expect(monitor).toBeVisible();
  await page.getByRole("tab", { name: /\.pipeline/ }).click();
  await page.screenshot({ path: "test-results/navigator-split.png" });
  await navTab.dragTo(page.locator("[data-editor-tabs='0']"));
  await expect(divider).toBeHidden();
  await expect(monitor.getByLabel("固定查看")).toBeChecked();
  await navTab.dragTo(area, { targetPosition: { x: 12, y: 130 } });
  await expect(page.locator("[data-editor-group='0']").getByRole("region")).toBeVisible();
  await expect(page.locator("[data-editor-group='1'] canvas")).toBeVisible();
  await expect(canvas).toHaveAttribute("data-instance", "original");
  await page.getByRole("tab", { name: "JSON", exact: true }).click();
  await expect(page.getByLabel("文件内容预览")).toHaveText(draft);
  await page.setViewportSize({ width: 600, height: 900 });
  await page.getByRole("button", { name: "收起右侧窗口", exact: true }).click();
  await expect(divider).toBeHidden();
  await page.getByRole("tab", { name: "Navigator", exact: true }).click();
  await expect(monitor.getByLabel("筛选监控节点")).toHaveValue("训练");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.setViewportSize({ width: 1600, height: 1000 });
  await expect(divider).toBeVisible();
  await expect(canvas).toHaveAttribute("data-instance", "original");
  // JSON is a movable document too, not a fixed canvas/monitor pairing.
  await page.getByRole("tab", { name: "JSON", exact: true }).dragTo(page.locator("[data-editor-tabs='0']"));
  await expect(page.locator("[data-editor-group='0']").getByLabel("文件内容预览")).toHaveText(draft);
  await expect(page.locator("[data-editor-group='1'] canvas")).toBeVisible();
  await page.reload();
  await expect(divider).toBeHidden();
  await expect(navTab).toBeVisible();
  await navTab.dragTo(area, { targetPosition: { x: (await area.boundingBox())!.width - 12, y: 130 } });
  await expect(divider).toBeVisible();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("cyrene.studio.layout.v1")!).editorRatio)).toBeCloseTo(ratio, 5);
  await page.getByLabel("语言", { exact: true }).selectOption("en-US");
  await expect(page.getByRole("separator", { name: "Resize editor split" })).toBeVisible();
  await expect(page.getByRole("region", { name: "Navigator run monitoring" }).getByRole("button", { name: "Unsplit editor" })).toBeVisible();
  await page.getByLabel("Language", { exact: true }).selectOption("zh-CN");
  await menuAction(page, "视图", "恢复默认布局");
  await expect(divider).toBeHidden();
  await expect(page.getByRole("tab", { name: "Navigator", exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
