import { menuAction } from "./ide-helpers";
import { expect, test } from "@playwright/test";

test("real server registry: create, edit, query, bind, persist, archive", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "服务器管理", exact: true }).click();
  const dialog = page.getByRole("complementary", { name: "服务器管理面板" });
  await expect(dialog.getByRole("button", { name: "保存服务器登记" })).toBeEnabled();
  const name = `测试算力-${Date.now()}`;
  await dialog.getByLabel("服务器名称").fill(name);
  await dialog.getByLabel("连接标识").fill("office-gpu-test");
  await dialog.getByLabel("区域", { exact: true }).fill("office");
  await dialog.getByRole("button", { name: "保存服务器登记" }).click();
  await expect(dialog.getByRole("button", { name: new RegExp(name) })).toBeVisible();
  await dialog.getByRole("button", { name: "查询连接状态" }).click();
  await expect(dialog.getByText("连接适配器尚未接入", { exact: false })).toBeVisible();
  await expect(dialog.getByText("未连接", { exact: true })).toBeVisible();
  await dialog.getByLabel("服务器名称").fill(`${name}-更新`);
  await dialog.getByRole("button", { name: "保存服务器登记" }).click();
  await expect(dialog.getByText(/修订 2/).first()).toBeVisible();
  await page.screenshot({ path: "test-results/studio-servers.png", fullPage: true });
  await page.getByRole("button", { name: "关闭服务器管理" }).click();
  await page.locator(".node-list summary").click();
  await page.locator(".node-list").getByRole("button", { name: /算力配置/ }).click();
  await page.getByRole("button", { name: "读取服务器登记" }).click();
  await page.getByLabel("选择目标服务器").selectOption({ label: `${name}-更新 · 自管服务器` });
  await expect(page.getByText("已选登记：", { exact: false })).toBeVisible();
  await menuAction(page, "文件", "保存草稿");
  const draft = await page.evaluate(() => JSON.parse(localStorage.getItem("cyrene.studio.prototype.v1.draft")!));
  expect(draft.nodes.find((n: { type: string }) => n.type === "compute").settingsBinding).toMatchObject({ kind: "server-registration", workspaceId: "local" });
  expect(JSON.stringify(draft)).not.toContain("office-gpu-test");
  await page.reload();
  await page.getByRole("button", { name: "服务器管理", exact: true }).click();
  await dialog.getByRole("button", { name: new RegExp(`${name}-更新`) }).click();
  await dialog.getByRole("button", { name: "归档登记" }).click();
  await expect(dialog.getByRole("button", { name: "保存服务器登记" })).toBeDisabled();
  await expect(dialog.getByText("目标服务器及其运行任务未被修改", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: "关闭服务器管理" }).click();
});
