// -----------------------------------------------------------------------------
// Module: services/catalyst/src/copy.ts
// Role: Short bilingual labels for the Catalyst trial workflow.
// 中文：为 Catalyst 试用流程提供精简中英操作标签。
// -----------------------------------------------------------------------------

type Locale = "zh-CN" | "en-US";

const chinese: Record<string, string> = {
  "Review original documents and prepare both outputs": "审核原始文档并生成两种数据包",
  "Keep original source files, review extracted passages, then build knowledge and training packages from approved content.": "保留原始来源文件并审核抽取段落，再从已批准内容构建知识与训练数据包。",
  "Supported source formats and batch limits": "支持的来源格式与批量上限",
  Dataset: "数据集",
  "Documents and published versions belong to this dataset.": "文档和已发布版本都归属于此数据集。",
  "Select a dataset": "选择数据集",
  "Upload source files": "上传来源文件",
  "Batch upload results": "批量上传结果",
  "Stored source revision": "已保存来源修订",
  "This upload can be retried.": "此文件可重试上传。",
  "Refresh data": "刷新数据",
  "Loading datasets": "正在读取数据集",
  "Reading the dataset list from Catalyst.": "正在读取 Catalyst 中的数据集列表。",
  "Loading...": "正在加载…",
  "Refreshing...": "正在刷新…",
  "Dataset list unavailable": "无法读取数据集",
  "Reconnect to Catalyst, then refresh this page.": "请重新连接 Catalyst，然后刷新此页面。",
  "Create a dataset first": "请先创建数据集",
  "Create a dataset container above to start a document review.": "先在上方创建数据集容器，再开始审核文档。",
  "Original documents": "原始文档",
  "Processing activity": "处理任务",
  "Review passages and generated drafts": "审核内容段落与生成草稿",
  "Review queue": "审核队列",
  "review items": "条审核事项",
  "PARSER AND GENERATED DRAFTS": "解析提醒与生成草稿",
  "Review queue unavailable": "无法读取审核队列",
  "Loading review queue": "正在读取审核队列",
  "Reading parser warnings and generated drafts.": "正在读取解析提醒和生成草稿。",
  "Parse reports unavailable": "无法读取解析报告",
  "Source revision": "来源修订",
  "Processing run": "处理任务",
  "Confidence": "置信度",
  "Severity": "级别",
  "Review required before approval.": "批准前必须完成审核。",
  "Parser warning": "解析提醒",
  "OCR warning": "OCR 识别提醒",
  "Document could not be read": "文档无法读取",
  "Unsupported file content": "不支持的文件内容",
  "Parser review": "解析审核",
  "OCR review": "OCR 审核",
  "Some embedded content could not be read.": "部分嵌入内容无法读取。",
  "This issue still blocks approval. Reprocess or exclude its source.": "此问题仍会阻止批准。请重新处理或排除此来源。",
  "Open related revision": "打开相关修订",
  "Acknowledge issue": "确认已审核",
  "Reject issue": "拒绝此项",
  "Generated draft": "生成草稿",
  "draft passages": "个草稿段落",
  "Review generated draft": "审核生成草稿",
  "No open review items": "没有待处理审核事项",
  "Parser warnings and generated drafts will appear here.": "解析提醒和生成草稿会显示在这里。",
  "Optional; kept with the review record.": "选填；此备注会保存在审核记录中。",
  "Parser review status is unavailable. Refresh before approving content.": "无法确认解析审核状态，请刷新后再批准内容。",
  "Resolve every applicable parser or OCR review item before approving.": "请先处理所有相关的解析或 OCR 审核事项。",
  "A parser warning has no review record yet. Refresh the queue before approving.": "解析提醒尚无对应审核记录，请刷新审核队列后再批准。",
  "Document parsing is still running for this revision.": "此修订的文档解析仍在进行中。",
  "Generation lineage": "生成来源记录",
  "Generation lineage is unavailable.": "当前草稿未提供生成来源记录。",
  "Recipe digest": "配方摘要",
  "Generated at": "生成时间",
  "Source passages": "来源段落",
  "Not reported": "未上报",
  "Build knowledge and training packages": "构建知识与训练数据包",
  "Training data curation": "训练数据整理",
  "JSON / JSONL · VERSIONED RECIPE": "JSON / JSONL · 版本化配方",
  "Import existing training rows, inspect detected formats and issues, then approve or exclude each record. Record decisions create an immutable child revision.": "导入已有训练样本，检查格式识别和问题，再逐条批准或排除。每次样本审核都会生成不可变子修订。",
  "Import training files": "导入训练文件",
  "JSON or JSONL files": "JSON 或 JSONL 文件",
  "Up to 20 files per batch; originals remain in the source ledger.": "每批最多 20 个文件；原件会保留在来源记录中。",
  "No JSON or JSONL sources yet": "尚无 JSON 或 JSONL 来源",
  "Choose training files above, or add JSON files in the source list.": "请在上方选择训练文件，或在来源列表中加入 JSON 文件。",
  "Detection and mapping": "格式识别与字段映射",
  "Input format": "输入格式",
  "Auto-detect common formats, or select one when detection is ambiguous.": "自动识别常见格式；识别不确定时可手动指定。",
  "Automatic detection": "自动识别",
  "Field mapping JSON": "字段映射 JSON",
  "Map canonical fields to source field names, for example {\"prompt\":\"question\"}.": "将标准字段映射到来源字段，例如 {\"prompt\":\"question\"}。",
  "Role mapping JSON": "角色映射 JSON",
  "Map custom source roles to system, user, or assistant explicitly.": "将自定义来源角色明确映射为 system、user 或 assistant。",
  "Minimum characters": "最少字符数",
  "Maximum characters": "最多字符数",
  "Training data use": "训练数据用途",
  "I confirm the selected sources are permitted for model training.": "我确认所选来源允许用于模型训练。",
  "Confirm that the selected sources are permitted for model training.": "请确认所选来源允许用于模型训练。",
  "Detect and normalize selected files": "识别并规范化所选文件",
  "Mappings must be valid JSON objects.": "映射必须是有效的 JSON 对象。",
  "Mappings must be valid JSON objects with string values.": "映射必须是值为字符串的有效 JSON 对象。",
  "Role mappings may target only system, user, or assistant.": "角色映射目标只能是 system、user 或 assistant。",
  "Select at least one JSON or JSONL source.": "请至少选择一个 JSON 或 JSONL 来源。",
  "No training files were stored.": "没有训练文件保存成功。",
  "Choose JSON or JSONL files only.": "请只选择 JSON 或 JSONL 文件。",
  "Training record review": "训练样本审核",
  "Training records unavailable": "无法读取训练样本",
  "Loading training records": "正在读取训练样本",
  "Reading one page of records from the immutable snapshot.": "正在从不可变快照读取一页记录。",
  "Snapshot artifact": "快照制品",
  "Total records": "记录总数",
  "Recognized": "识别成功",
  "Format errors": "格式错误",
  "Duplicate candidates": "重复候选",
  "Pending review": "待审核",
  "Excluded": "已排除",
  "Eligible": "可用",
  "The recognized, format-error, and duplicate counts can overlap. Eligible, pending-review, and excluded counts add up to the total.": "识别成功、格式错误和重复候选数可能重叠；可用、待审核和已排除数量之和等于总数。",
  "Disposition": "处理状态",
  "All records": "全部记录",
  "Issue type or code": "问题类型或代码",
  "Filter by issue code": "按问题代码筛选",
  "No records match these filters": "没有符合筛选条件的记录",
  "Change the issue or disposition filters to see other records.": "修改问题或处理状态筛选以查看其他记录。",
  "Previous page": "上一页",
  "Next page": "下一页",
  "records": "条记录",
  "Source family": "来源族",
  "Conversation ID": "对话标识",
  "Location": "位置",
  "No detected issues.": "未发现问题。",
  "Compare original and normalized messages": "对比原始记录与规范化消息",
  "Original record": "原始记录",
  "Normalized messages": "规范化消息",
  "Processing history and manual correction": "处理历史与人工修正",
  "Corrected original fields JSON": "修正后的原始字段 JSON",
  "Keep the source fields and edit only values that need correction. The original remains in the prior revision.": "保留来源字段，只修改需要修正的值。原始版本仍保留在上一修订中。",
  "Corrected source fields must be valid JSON.": "修正后的来源字段必须是有效 JSON。",
  "Corrected source fields must be a JSON object.": "修正后的来源字段必须是 JSON 对象。",
  "Approve record": "批准样本",
  "Apply manual field and role mapping": "应用人工字段和角色映射",
  "Exclude record": "排除样本",
  "Training sample": "训练样本",
  "Review training samples": "审核训练样本",
  "Training use policy": "训练用途策略",
  Allowed: "允许",
  Blocked: "禁止",
  "Content digest": "内容摘要",
  "Record disposition counts do not reconcile with the total. Publishing remains blocked until Catalyst reports consistent counts.": "记录处理状态数量与总数不一致。Catalyst 上报一致数量前会阻止发布。",
  "Training data structure issue": "训练数据结构问题",
  "Possible duplicate training sample": "可能重复的训练样本",
  "Training sample quality warning": "训练样本质量提醒",
  "Unsupported training sample content": "不支持的训练样本内容",
  "Possible training split leakage": "可能存在训练集划分泄漏",
  "Training output target": "训练数据输出目标",
  "Messages keeps every supported turn; prompt-completion accepts only representable single-turn samples.": "messages 格式会保留支持的所有轮次；prompt-completion 只接受可表达的单轮样本。",
  "Trainer SFT JSONL": "训练器兼容的 SFT JSONL",
  "Conversational messages JSONL": "对话 messages JSONL",
  "Prompt-completion JSONL": "Prompt-completion JSONL",
  "This version contains the reviewed SFT package.": "此版本包含已审核的 SFT 数据包。",
  "Publish SFT package": "发布 SFT 数据包",
  "Training package built": "训练数据包已构建",
  eligible: "可用",
  review: "待审核",
  excluded: "已排除",
  "Published data versions": "已发布数据版本",
  "Sources unavailable": "无法读取来源文件",
  "Loading original files": "正在读取原始文件",
  "Reading the source ledger from Catalyst.": "正在读取 Catalyst 中的来源记录。",
  "No original documents yet": "尚无原始文档",
  "Upload supported source files. Catalyst retains the exact original bytes.": "上传支持的来源文件。Catalyst 会保留原始文件字节。",
  "SOURCE FILES": "来源文件",
  "Upload a PDF or DOCX file. The exact original bytes are retained by Catalyst.": "上传 PDF 或 DOCX 文件。Catalyst 会保留原始文件字节。",
  "This file exceeds the 32 MiB upload limit.": "文件超过 32 MiB 上传上限。",
  "This file could not be stored because the per-file or batch upload limit was reached.": "单文件或批次上传已达到大小上限，无法保存此文件。",
  "This file exceeds the 32 MiB per-file upload limit.": "文件超过 32 MiB 单文件上传上限。",
  "The batch reached its 128 MiB stored-file limit. This file was not stored.": "此批次已达到 128 MiB 文件总量上限，因此未保存此文件。",
  "This file could not be staged in the workspace. Try again or ask an administrator to check storage configuration.": "无法在工作空间保存此文件。请重试，或联系管理员检查存储配置。",
  "This file type cannot be extracted. The original file remains available for download.": "无法从此文件类型中提取内容，但原始文件仍可下载。",
  "No readable content was extracted. Check whether the file is damaged, protected, or image-only.": "未能提取可读内容。请检查文件是否损坏、受保护或仅包含图像。",
  "This source could not be read. Review the file and try parsing it again.": "无法读取此来源。请检查文件后重试解析。",
  "The batch request exceeds the 129 MiB upload limit. Select fewer or smaller files.": "批量请求超过 129 MiB 上限，请减少文件数量或选择较小的文件。",
  "A batch can include at most 20 files.": "每批最多可包含 20 个文件。",
  "Choose at least one source file.": "请至少选择一个来源文件。",
  "Choose a PDF or Word document (.docx).": "请选择 PDF 或 Word 文档（.docx）。",
  "This file type is unsupported. Choose a PDF or Word document (.docx).": "不支持此文件类型。请选择 PDF 或 Word 文档（.docx）。",
  "This capability is not configured for this workspace. Ask an administrator to enable it.": "此工作空间尚未配置该能力，请联系管理员启用。",
  "You do not have permission to make this change. Sign in again or ask an administrator.": "你没有权限执行此操作。请重新登录或联系管理员。",
  "This step could not run because a workspace capability is unavailable. Ask an administrator to check the configuration.": "此步骤无法运行，因为工作空间缺少所需配置。请联系管理员检查。",
  "Catalyst did not return a downloadable package.": "Catalyst 未返回可下载的数据包。",
  "The request could not be completed. Try again.": "请求未能完成，请重试。",
  "The request could not be completed.": "请求未能完成。",
  "Processing status unavailable": "无法读取处理状态",
  "Loading processing status": "正在读取处理状态",
  "Reading recent work from Catalyst.": "正在读取 Catalyst 中的近期任务。",
  "No processing activity": "尚无处理任务",
  "LIVE STATUS": "实时状态",
  "Uploading a document will start its first review run.": "上传文档后会启动首次解析与校对。",
  sources: "个来源文件",
  runs: "个任务",
  revisions: "个内容修订",
  versions: "个版本",
  "Content revisions unavailable": "无法读取内容修订",
  "IMMUTABLE REVISIONS": "不可变修订记录",
  "Loading content": "正在读取内容",
  "Reading revision history from Catalyst.": "正在读取 Catalyst 中的修订历史。",
  "Content revision": "内容修订",
  "source revisions": "个来源修订",
  "Revision": "修订",
  "generated drafts": "条生成草稿",
  "Loading passages": "正在读取内容段落",
  "Reading document text and page locations.": "正在读取文档文本和页码位置。",
  "Passages unavailable": "无法读取内容段落",
  "No passages in this revision": "此修订中没有内容段落",
  "No content to review yet": "尚无待审核内容",
  "Upload and process a PDF or DOCX file to create the first content revision.": "上传并解析 PDF 或 DOCX 文件，即可生成首个内容修订。",
  "The processing run may have failed or the document may contain no readable text.": "处理任务可能失败，或文档中没有可读取的文本。",
  "Content use is blocked by default. Choose the package and allowed use for each passage, add its allowed people or groups, and approve the revision when review is complete.": "内容默认禁止使用。请为每个段落选择数据包和允许用途、填写获准人员或群组，并在审核完成后批准修订。",
  "Review note": "审核备注",
  "Review note:": "审核备注：",
  "Optional; kept with the revision for reviewers.": "选填；此备注会保存在修订记录中，供审核者查看。",
  "Add a note for the review record": "填写审核备注",
  "Approve content": "批准内容",
  "Reject revision": "拒绝此修订",
  "Save new revision": "保存为新修订",
  "Passage text": "段落内容",
  "Include in knowledge": "加入知识库",
  "Include in training": "加入训练数据",
  "Allow knowledge retrieval use": "允许用于知识检索",
  "Allow model training use": "允许用于模型训练",
  "Allowed people or groups": "允许使用的人员或群组",
  "One allowed principal reference per line": "每行填写一个允许使用的人员或群组标识",
  "Leave blank to deny access to this passage.": "留空表示不允许使用此段落。",
  "Approved content is ready for both recipes. Changes create a new revision.": "已批准内容可用于两种配方。修改内容会创建新的修订。",
  "Approve content before building": "构建前请先批准内容",
  "Select an approved revision or review and approve the current passages first.": "请选择已批准的修订，或先审核并批准当前段落。",
  "Searchable knowledge package": "可检索的知识数据包",
  "Train, validation, and test data": "训练、验证和测试数据",
  "Generate questions and answers for review": "生成问答草稿供审核",
  "Maximum examples": "最多生成样例数",
  "Maximum model calls": "最多调用次数",
  "SFT format": "训练数据格式",
  Instruction: "指令格式",
  Conversation: "对话格式",
  "Train %": "训练集 %",
  "Validation %": "验证集 %",
  "Test %": "测试集 %",
  "Split percentages must add up to 100.": "数据划分比例总和必须为 100%。",
  "Publish both packages": "发布两个数据包",
  "Published versions unavailable": "无法读取已发布版本",
  "IMMUTABLE VERSIONS": "不可变版本",
  "Loading published versions": "正在读取已发布版本",
  "Reading immutable versions from Catalyst.": "正在读取 Catalyst 中的不可变版本。",
  "No published data versions": "尚无已发布的数据版本",
  "Build both packages from approved content, then publish them together.": "从已批准内容构建两个数据包，再一起发布。",
  "Ready to publish": "可以发布",
  "One version will include both approved package artifacts.": "一个版本将同时包含两个已批准的数据包。",
  "Ready to publish from the latest successful run.": "已有最新成功任务，可用于发布。",
  "Download knowledge package": "下载知识数据包",
  "Download training package": "下载训练数据包",
  "Dataset version": "数据集版本",
  "This version was published through the existing preparation flow.": "此版本通过现有的数据准备流程发布。",
  "Package downloads are available for data-tools versions.": "数据工具版本支持下载数据包。",
  "OUT OF DATE": "内容已更新",
  CURRENT: "当前版本",
  "LEGACY VERSION": "既有版本",
  UPLOADED: "已上传",
  PROCESSING: "处理中",
  "READY TO REVIEW": "待审核",
  FAILED: "失败",
  INTERRUPTED: "已中断",
  CANCELLED: "已取消",
  QUEUED: "排队中",
  RUNNING: "运行中",
  SUCCEEDED: "已完成",
  WARNING: "需审核",
  warning: "警告",
  error: "错误",
  DRAFT: "待审核",
  APPROVED: "已批准",
  REJECTED: "已拒绝",
  OPEN: "待审核",
  ACKNOWLEDGED: "已确认",
  "Document review": "文档解析与校对",
  "Build knowledge package": "构建知识数据包",
  "Build training package": "构建训练数据包",
  "Generate draft questions": "生成问答草稿",
  Block: "段落",
  Paragraph: "正文",
  Table: "表格",
  Picture: "图片",
  Form: "表单",
  "Question and answer": "问答",
  EXTRACTED: "已抽取",
  NORMALIZED: "已整理",
  "HUMAN EDITED": "人工修订",
  "GENERATED DRAFT": "生成草稿",
  Page: "第",
  Pages: "第",
  "Location not provided": "未提供原文位置",
  "Date not reported": "未提供时间",
  Recipe: "配方",
  Budget: "预算",
  Usage: "用量",
  Model: "模型",
  "This step did not finish. Review the status and try again if the action is available.": "此步骤未能完成。请检查状态；如有重试操作，可再次尝试。",
  "Cancellation was requested. The final status will appear here.": "已请求取消，最终状态会在此显示。",
  "A new run was created. The earlier run remains in the activity list.": "已创建新任务，先前任务仍保留在任务列表中。",
  "Previous revisions remain available.": "先前修订仍可查看。",
  "Could not refresh this run's status.": "无法刷新此任务状态。",
  "TWO EXPLICIT RECIPES": "两种明确的数据配方",
  KNOWLEDGE: "知识库",
  TRAINING: "训练数据",
  "OPTIONAL DRAFT GENERATION": "可选：生成问答草稿",
  "Build cited passages with page locations, source history, and use policies.": "构建带页码、来源历史和使用策略的可引用内容段落。",
  "Create a deterministic split by source or conversation family.": "按来源或对话系列生成可复现的数据划分。",
  "Generation is an explicit action with a visible budget. Generated passages remain drafts until you approve them.": "问答生成需要显式启动，并显示调用预算。生成内容会保留为草稿，批准后才可使用。",
  "Package inclusion": "数据包收录设置",
  "Unnamed dataset": "未命名数据集",
  "Some page content could not be read. Review the extracted passages before approving.": "部分页面内容无法读取。批准前请检查已抽取的段落。",
  "Some document content may be missing. Review the extracted passages before approving.": "文档内容可能不完整。批准前请检查已抽取的段落。",
  "Review the extracted content before approving.": "批准前请检查已抽取的内容。",
  Cancel: "取消任务",
  Retry: "重试任务",
  "Try again": "重试",
  "Load more passages": "加载更多段落",
  "Working in": "当前数据集：",
  "Uploading the file and starting document review...": "正在上传文件并启动文档解析与校对…",
  "Document workflow progress": "文档处理流程进度",
  "CATALYST DATA TOOLS": "文档数据工具",
};

/** Translate only the high-value labels used by this trial module. */
export function catalystText(value: string, locale: Locale): string {
  return locale === "zh-CN" ? chinese[value] ?? value : value;
}
